### ISSUE TITLE
Question sur l'échelle des images

### ISSUE THREAD

**Issue by deepcharles** [LucasJacquier/LumIn-microscopie-fluorescence#3]
Quand on charge les images, l'intensité va de ~100 à ~1200. Il faudrait mettre à l'échelle entre 0 et une valeur maximale (255 si image 8-bit). Mais pour cela il faut connaitre la valeur minimale et la valeur maximale possibles. A demander aux physiciens.

**Comment by LucasJacquier** [comment]
ah oui en effet, on ne peut pas le faire informatiquement, en cherchant la valeur maximale de l'échantillon et en étalant les données entre max et min ? 
Ou alors faire un critère pour éviter les valeurs extrêmes

**Comment by LucasJacquier** [comment]
J'ai crée une fonction qui élimine les valeurs aberrantes. C'est simplement une fonction qui retire le pourcentage des valeurs les plus importantes. On a maintenant des valeurs allant de 0 à 150/200 environ. 
Je pensais faire une fonction pour remplacer toutes les données par un étalement linéaire pour que le maximum soit fixé à 255, t'en penses quoi ?

**Comment by deepcharles** [comment]
Pourquoi pas. Est-ce Karen a une idée de la valeur maximale que peut prendre l'intensité ?

**Comment by LucasJacquier** [comment]
Je ne sais pas, je voulais écrire un message mais je pense pas qu'il y ait des notions physiques derrière. C'est juste l'instrument de mesure qui déconne. 

Bon, en fait ma fonction n'est pas très performante, parce que même 1% des valeurs en fait ca en fait beaucoup trop, je vais la modifier

**Comment by deepcharles** [comment]
Demande quand même. On sera fixés.

**Comment by LucasJacquier** [comment]
Je viens de demander. 
Il semble y avoir aussi un décalage entre le film vert et le film rouge. Le film rouge a des valeurs bien plus hautes en moyenne, à ce qu'il semble.

Là j'essaye de réétaler les valeurs sur l'intervalle 0;255

**Comment by LucasJacquier** [comment]
D'après Karen, les valeurs très élevés sont normales, ce sont les points de fluorescence : "bonjour Lucas, je pense que ce sont justement ces valeurs élevées qui correspondent aux points de fluorescence. Les pixels à 200 sont du bruit. Je reconnais que la valeur à 7000 doit être un agrégat très fluorescent et pas une molécule unique". 
Je pense qu'il y a aussi des valeurs aberrantes mais c'est vrai qu'il ne faut pas trop étêter le signal car ce sont les valeurs élevées qui nous intéresse.

**Comment by deepcharles** [comment]
ok, c'est noté. Gardons ce point en mémoire et passons à la détection de pics.
